"""Rebuild city-only frontend summaries from the served rasters (requires rasterio)."""
import json
from pathlib import Path

import numpy as np
import rasterio

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def read(relative):
    with rasterio.open(DATA / relative) as src:
        return src.read(1, masked=True)


baseline = read("webapp_rasters/climatology_mean_2013_2026_30m.tif")
details = {}
for year in range(2013, 2027):
    lst = read(f"gee_lst/Bologna_LST_{year}_summer_median_30m.tif")
    values = lst.compressed()
    hotspot = read(f"hotspots/hotspot_temporal_{year}_zgt1p0.tif")
    details[year] = {
        "count": int(values.size),
        "mean": float(values.mean()),
        "anomalyMean": float((lst - baseline).mean()),
        "median": float(np.percentile(values, 50)),
        "p95": float(np.percentile(values, 95)),
        "hotspotFraction": float((hotspot > 0).mean() * 100),
    }

output = "// Generated by scripts/build_yearly_stats.py from city-clipped rasters.\n"
output += "export const visibleYearlyLstStats = " + json.dumps(details, indent=2) + ";\n"
output += "export const yearlyStats = Object.entries(visibleYearlyLstStats).map(([year, row]) => ({\n"
output += "  year: Number(year), lst: row.mean, anomaly: row.anomalyMean, hotspot: row.hotspotFraction,\n"
output += "}));\n"
(ROOT / "src/data/yearlyStats.js").write_text(output, encoding="utf-8")
print(f"Generated {len(details)} city-only yearly summaries")
